### ISSUE TITLE
unable to build

### ISSUE THREAD

**Issue by fone** [MartijnBraam/python-isc-dhcp-leases#15]
I'm having trouble building this. Any idea what might be the trouble?
thanks.

python setup.py build

`
/usr/lib64/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
running build
running build_py
creating build
creating build/lib
creating build/lib/isc_dhcp_leases
copying isc_dhcp_leases/__init__.py -> build/lib/isc_dhcp_leases
copying isc_dhcp_leases/iscdhcpleases.py -> build/lib/isc_dhcp_leases
copying isc_dhcp_leases/test_iscDhcpLeases.py -> build/lib/isc_dhcp_leases
copying isc_dhcp_leases/test_lease.py -> build/lib/isc_dhcp_leases
copying isc_dhcp_leases/test_lease6.py -> build/lib/isc_dhcp_leases
`

**Comment by andir** [comment]
Maybe http://stackoverflow.com/a/10686196 ?

**Comment by andir** [comment]
I guess this can be closed @MartijnBraam

**Comment by MartijnBraam** [comment]
Yeah, seems so. Not a problem with this code.
