### ISSUE TITLE
iaid endianness/signed incorrect

### ISSUE THREAD

**Issue by freddy36** [MartijnBraam/python-isc-dhcp-leases#6]
iaid is incorrectly unpacked (wrong endianess and as signed integer), it should be:
`self.iaid = struct.unpack('<I', self.host_identifier[0:4])[0]`
instead of
`self.iaid = struct.unpack('>i', self.host_identifier[0:4])[0`

**Comment by MartijnBraam** [comment]
Oops, changed it
